// Mocks generated by Mockito 5.4.6 from annotations
// in yolo/test/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i14;

import 'package:flutter/services.dart' as _i11;
import 'package:flutter_bloc/flutter_bloc.dart' as _i21;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i16;
import 'package:ultralytics_yolo/models/yolo_task.dart' as _i12;
import 'package:ultralytics_yolo/widgets/yolo_controller.dart' as _i10;
import 'package:ultralytics_yolo/yolo_streaming_config.dart' as _i13;
import 'package:yolo/application/blocs/camera_inference/camera_inference_bloc.dart'
    as _i19;
import 'package:yolo/application/blocs/camera_inference/camera_inference_event.dart'
    as _i20;
import 'package:yolo/application/blocs/camera_inference/camera_inference_state.dart'
    as _i2;
import 'package:yolo/data/datasources/download_progress.dart' as _i18;
import 'package:yolo/data/datasources/local_model_data_source.dart' as _i15;
import 'package:yolo/data/datasources/remote_model_data_source.dart' as _i17;
import 'package:yolo/domain/entities/model_loading_state.dart' as _i7;
import 'package:yolo/domain/entities/models.dart' as _i8;
import 'package:yolo/domain/entities/system_health_state.dart' as _i9;
import 'package:yolo/domain/entities/system_metrics.dart' as _i5;
import 'package:yolo/domain/repositories/system_monitor_repository.dart' as _i3;
import 'package:yolo/domain/repositories/yolo_repository.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCameraInferenceState_0 extends _i1.SmartFake
    implements _i2.CameraInferenceState {
  _FakeCameraInferenceState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SystemMonitorRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSystemMonitorRepository extends _i1.Mock
    implements _i3.SystemMonitorRepository {
  MockSystemMonitorRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.SystemMetrics> get metricsStream =>
      (super.noSuchMethod(
            Invocation.getter(#metricsStream),
            returnValue: _i4.Stream<_i5.SystemMetrics>.empty(),
          )
          as _i4.Stream<_i5.SystemMetrics>);

  @override
  void start({Duration? interval = const Duration(minutes: 5)}) =>
      super.noSuchMethod(
        Invocation.method(#start, [], {#interval: interval}),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [YoloRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockYoloRepository extends _i1.Mock implements _i6.YoloRepository {
  MockYoloRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i7.ModelLoadingState> getModelPath(_i8.ModelType? modelType) =>
      (super.noSuchMethod(
            Invocation.method(#getModelPath, [modelType]),
            returnValue: _i4.Stream<_i7.ModelLoadingState>.empty(),
          )
          as _i4.Stream<_i7.ModelLoadingState>);

  @override
  _i4.Future<void> setConfidenceThreshold(double? threshold) =>
      (super.noSuchMethod(
            Invocation.method(#setConfidenceThreshold, [threshold]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setIoUThreshold(double? threshold) =>
      (super.noSuchMethod(
            Invocation.method(#setIoUThreshold, [threshold]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setNumItemsThreshold(int? threshold) =>
      (super.noSuchMethod(
            Invocation.method(#setNumItemsThreshold, [threshold]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setThresholds({
    required double? confidenceThreshold,
    required double? iouThreshold,
    required int? numItemsThreshold,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setThresholds, [], {
              #confidenceThreshold: confidenceThreshold,
              #iouThreshold: iouThreshold,
              #numItemsThreshold: numItemsThreshold,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setStreamingConfig(_i9.SystemHealthState? healthState) =>
      (super.noSuchMethod(
            Invocation.method(#setStreamingConfig, [healthState]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [YOLOViewController].
///
/// See the documentation for Mockito's code generation for more information.
class MockYOLOViewController extends _i1.Mock
    implements _i10.YOLOViewController {
  MockYOLOViewController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  double get confidenceThreshold =>
      (super.noSuchMethod(
            Invocation.getter(#confidenceThreshold),
            returnValue: 0.0,
          )
          as double);

  @override
  double get iouThreshold =>
      (super.noSuchMethod(Invocation.getter(#iouThreshold), returnValue: 0.0)
          as double);

  @override
  int get numItemsThreshold =>
      (super.noSuchMethod(Invocation.getter(#numItemsThreshold), returnValue: 0)
          as int);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  void init(_i11.MethodChannel? methodChannel, int? viewId) =>
      super.noSuchMethod(
        Invocation.method(#init, [methodChannel, viewId]),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> setConfidenceThreshold(double? threshold) =>
      (super.noSuchMethod(
            Invocation.method(#setConfidenceThreshold, [threshold]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setIoUThreshold(double? threshold) =>
      (super.noSuchMethod(
            Invocation.method(#setIoUThreshold, [threshold]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setNumItemsThreshold(int? numItems) =>
      (super.noSuchMethod(
            Invocation.method(#setNumItemsThreshold, [numItems]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setThresholds({
    double? confidenceThreshold,
    double? iouThreshold,
    int? numItemsThreshold,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setThresholds, [], {
              #confidenceThreshold: confidenceThreshold,
              #iouThreshold: iouThreshold,
              #numItemsThreshold: numItemsThreshold,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> switchCamera() =>
      (super.noSuchMethod(
            Invocation.method(#switchCamera, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> zoomIn() =>
      (super.noSuchMethod(
            Invocation.method(#zoomIn, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> zoomOut() =>
      (super.noSuchMethod(
            Invocation.method(#zoomOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setZoomLevel(double? zoomLevel) =>
      (super.noSuchMethod(
            Invocation.method(#setZoomLevel, [zoomLevel]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> switchModel(String? modelPath, _i12.YOLOTask? task) =>
      (super.noSuchMethod(
            Invocation.method(#switchModel, [modelPath, task]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setStreamingConfig(_i13.YOLOStreamingConfig? config) =>
      (super.noSuchMethod(
            Invocation.method(#setStreamingConfig, [config]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setShowUIControls(bool? show) =>
      (super.noSuchMethod(
            Invocation.method(#setShowUIControls, [show]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setShowOverlays(bool? show) =>
      (super.noSuchMethod(
            Invocation.method(#setShowOverlays, [show]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i14.Uint8List?> captureFrame() =>
      (super.noSuchMethod(
            Invocation.method(#captureFrame, []),
            returnValue: _i4.Future<_i14.Uint8List?>.value(),
          )
          as _i4.Future<_i14.Uint8List?>);
}

/// A class which mocks [LocalModelDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalModelDataSource extends _i1.Mock
    implements _i15.LocalModelDataSource {
  MockLocalModelDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String?> getModelPath(_i8.ModelType? modelType) =>
      (super.noSuchMethod(
            Invocation.method(#getModelPath, [modelType]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<String> saveModel(
    _i8.ModelType? modelType,
    _i14.Uint8List? bytes,
    bool? isZip,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#saveModel, [modelType, bytes, isZip]),
            returnValue: _i4.Future<String>.value(
              _i16.dummyValue<String>(
                this,
                Invocation.method(#saveModel, [modelType, bytes, isZip]),
              ),
            ),
          )
          as _i4.Future<String>);
}

/// A class which mocks [RemoteModelDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteModelDataSource extends _i1.Mock
    implements _i17.RemoteModelDataSource {
  MockRemoteModelDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i18.DownloadProgress> downloadModel(_i8.ModelType? modelType) =>
      (super.noSuchMethod(
            Invocation.method(#downloadModel, [modelType]),
            returnValue: _i4.Stream<_i18.DownloadProgress>.empty(),
          )
          as _i4.Stream<_i18.DownloadProgress>);
}

/// A class which mocks [CameraInferenceBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockCameraInferenceBloc extends _i1.Mock
    implements _i19.CameraInferenceBloc {
  MockCameraInferenceBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CameraInferenceState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeCameraInferenceState_0(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i2.CameraInferenceState);

  @override
  _i4.Stream<_i2.CameraInferenceState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i4.Stream<_i2.CameraInferenceState>.empty(),
          )
          as _i4.Stream<_i2.CameraInferenceState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i4.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void add(_i20.CameraInferenceEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i20.CameraInferenceEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i2.CameraInferenceState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i20.CameraInferenceEvent>(
    _i21.EventHandler<E, _i2.CameraInferenceState>? handler, {
    _i21.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i21.Transition<_i20.CameraInferenceEvent, _i2.CameraInferenceState>?
    transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i20.CameraInferenceEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i21.Change<_i2.CameraInferenceState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
