// Mocks generated by Mockito 5.4.6 from annotations
// in yolo/test/application/widgets/camera_inference_content_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i7;

import 'package:flutter/services.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:ultralytics_yolo/models/yolo_task.dart' as _i5;
import 'package:ultralytics_yolo/widgets/yolo_controller.dart' as _i2;
import 'package:ultralytics_yolo/yolo_streaming_config.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [YOLOViewController].
///
/// See the documentation for Mockito's code generation for more information.
class MockYOLOViewController extends _i1.Mock
    implements _i2.YOLOViewController {
  MockYOLOViewController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  double get confidenceThreshold =>
      (super.noSuchMethod(
            Invocation.getter(#confidenceThreshold),
            returnValue: 0.0,
          )
          as double);

  @override
  double get iouThreshold =>
      (super.noSuchMethod(Invocation.getter(#iouThreshold), returnValue: 0.0)
          as double);

  @override
  int get numItemsThreshold =>
      (super.noSuchMethod(Invocation.getter(#numItemsThreshold), returnValue: 0)
          as int);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  void init(_i3.MethodChannel? methodChannel, int? viewId) =>
      super.noSuchMethod(
        Invocation.method(#init, [methodChannel, viewId]),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> setConfidenceThreshold(double? threshold) =>
      (super.noSuchMethod(
            Invocation.method(#setConfidenceThreshold, [threshold]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setIoUThreshold(double? threshold) =>
      (super.noSuchMethod(
            Invocation.method(#setIoUThreshold, [threshold]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setNumItemsThreshold(int? numItems) =>
      (super.noSuchMethod(
            Invocation.method(#setNumItemsThreshold, [numItems]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setThresholds({
    double? confidenceThreshold,
    double? iouThreshold,
    int? numItemsThreshold,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#setThresholds, [], {
              #confidenceThreshold: confidenceThreshold,
              #iouThreshold: iouThreshold,
              #numItemsThreshold: numItemsThreshold,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> switchCamera() =>
      (super.noSuchMethod(
            Invocation.method(#switchCamera, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> zoomIn() =>
      (super.noSuchMethod(
            Invocation.method(#zoomIn, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> zoomOut() =>
      (super.noSuchMethod(
            Invocation.method(#zoomOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setZoomLevel(double? zoomLevel) =>
      (super.noSuchMethod(
            Invocation.method(#setZoomLevel, [zoomLevel]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> switchModel(String? modelPath, _i5.YOLOTask? task) =>
      (super.noSuchMethod(
            Invocation.method(#switchModel, [modelPath, task]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setStreamingConfig(_i6.YOLOStreamingConfig? config) =>
      (super.noSuchMethod(
            Invocation.method(#setStreamingConfig, [config]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setShowUIControls(bool? show) =>
      (super.noSuchMethod(
            Invocation.method(#setShowUIControls, [show]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setShowOverlays(bool? show) =>
      (super.noSuchMethod(
            Invocation.method(#setShowOverlays, [show]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i7.Uint8List?> captureFrame() =>
      (super.noSuchMethod(
            Invocation.method(#captureFrame, []),
            returnValue: _i4.Future<_i7.Uint8List?>.value(),
          )
          as _i4.Future<_i7.Uint8List?>);
}
