// Mocks generated by Mockito 5.4.6 from annotations
// in yolo/test/application/blocs/camera_inference/camera_inference_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:yolo/domain/entities/model_loading_state.dart' as _i5;
import 'package:yolo/domain/entities/models.dart' as _i6;
import 'package:yolo/domain/entities/system_health_state.dart' as _i19;
import 'package:yolo/domain/entities/system_metrics.dart' as _i14;
import 'package:yolo/domain/repositories/system_monitor_repository.dart' as _i2;
import 'package:yolo/domain/usecases/flip_camera.dart' as _i7;
import 'package:yolo/domain/usecases/get_model_path.dart' as _i3;
import 'package:yolo/domain/usecases/get_system_metrics.dart' as _i13;
import 'package:yolo/domain/usecases/set_confidence_threshold.dart' as _i8;
import 'package:yolo/domain/usecases/set_iou_threshold.dart' as _i9;
import 'package:yolo/domain/usecases/set_num_items_threshold.dart' as _i10;
import 'package:yolo/domain/usecases/set_streaming_config.dart' as _i18;
import 'package:yolo/domain/usecases/set_thresholds.dart' as _i12;
import 'package:yolo/domain/usecases/set_zoom_level.dart' as _i11;
import 'package:yolo/domain/usecases/system_metrics_monitor_dispose.dart'
    as _i16;
import 'package:yolo/domain/usecases/system_metrics_monitor_start.dart' as _i15;
import 'package:yolo/domain/usecases/system_metrics_monitor_stop.dart' as _i17;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSystemMonitorRepository_0 extends _i1.SmartFake
    implements _i2.SystemMonitorRepository {
  _FakeSystemMonitorRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetModelPath].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetModelPath extends _i1.Mock implements _i3.GetModelPath {
  MockGetModelPath() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.ModelLoadingState> call(_i6.ModelType? modelType) =>
      (super.noSuchMethod(
            Invocation.method(#call, [modelType]),
            returnValue: _i4.Stream<_i5.ModelLoadingState>.empty(),
          )
          as _i4.Stream<_i5.ModelLoadingState>);
}

/// A class which mocks [FlipCamera].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlipCamera extends _i1.Mock implements _i7.FlipCamera {
  MockFlipCamera() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void call() => super.noSuchMethod(
    Invocation.method(#call, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SetConfidenceThreshold].
///
/// See the documentation for Mockito's code generation for more information.
class MockSetConfidenceThreshold extends _i1.Mock
    implements _i8.SetConfidenceThreshold {
  MockSetConfidenceThreshold() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void call(double? threshold) => super.noSuchMethod(
    Invocation.method(#call, [threshold]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SetIoUThreshold].
///
/// See the documentation for Mockito's code generation for more information.
class MockSetIoUThreshold extends _i1.Mock implements _i9.SetIoUThreshold {
  MockSetIoUThreshold() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void call(double? threshold) => super.noSuchMethod(
    Invocation.method(#call, [threshold]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SetNumItemsThreshold].
///
/// See the documentation for Mockito's code generation for more information.
class MockSetNumItemsThreshold extends _i1.Mock
    implements _i10.SetNumItemsThreshold {
  MockSetNumItemsThreshold() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void call(int? threshold) => super.noSuchMethod(
    Invocation.method(#call, [threshold]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SetZoomLevel].
///
/// See the documentation for Mockito's code generation for more information.
class MockSetZoomLevel extends _i1.Mock implements _i11.SetZoomLevel {
  MockSetZoomLevel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void call(double? zoomLevel) => super.noSuchMethod(
    Invocation.method(#call, [zoomLevel]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SetThresholds].
///
/// See the documentation for Mockito's code generation for more information.
class MockSetThresholds extends _i1.Mock implements _i12.SetThresholds {
  MockSetThresholds() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void call({
    required double? confidenceThreshold,
    required double? iouThreshold,
    required int? numItemsThreshold,
  }) => super.noSuchMethod(
    Invocation.method(#call, [], {
      #confidenceThreshold: confidenceThreshold,
      #iouThreshold: iouThreshold,
      #numItemsThreshold: numItemsThreshold,
    }),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [GetSystemMetrics].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSystemMetrics extends _i1.Mock implements _i13.GetSystemMetrics {
  MockGetSystemMetrics() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SystemMonitorRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeSystemMonitorRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.SystemMonitorRepository);

  @override
  _i4.Stream<_i14.SystemMetrics> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Stream<_i14.SystemMetrics>.empty(),
          )
          as _i4.Stream<_i14.SystemMetrics>);
}

/// A class which mocks [SystemMetricsMonitorStart].
///
/// See the documentation for Mockito's code generation for more information.
class MockSystemMetricsMonitorStart extends _i1.Mock
    implements _i15.SystemMetricsMonitorStart {
  MockSystemMetricsMonitorStart() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SystemMonitorRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeSystemMonitorRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.SystemMonitorRepository);

  @override
  void call({Duration? interval = const Duration(minutes: 5)}) =>
      super.noSuchMethod(
        Invocation.method(#call, [], {#interval: interval}),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [SystemMetricsMonitorDispose].
///
/// See the documentation for Mockito's code generation for more information.
class MockSystemMetricsMonitorDispose extends _i1.Mock
    implements _i16.SystemMetricsMonitorDispose {
  MockSystemMetricsMonitorDispose() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SystemMonitorRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeSystemMonitorRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.SystemMonitorRepository);

  @override
  _i4.Future<void> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [SystemMetricsMonitorStop].
///
/// See the documentation for Mockito's code generation for more information.
class MockSystemMetricsMonitorStop extends _i1.Mock
    implements _i17.SystemMetricsMonitorStop {
  MockSystemMetricsMonitorStop() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SystemMonitorRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeSystemMonitorRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.SystemMonitorRepository);

  @override
  _i4.Future<void> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [SetStreamingConfig].
///
/// See the documentation for Mockito's code generation for more information.
class MockSetStreamingConfig extends _i1.Mock
    implements _i18.SetStreamingConfig {
  MockSetStreamingConfig() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> call(_i19.SystemHealthState? health) =>
      (super.noSuchMethod(
            Invocation.method(#call, [health]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
